
name: Autocorrección de HTML

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Instalar dependencias
      run: npm install htmlhint

    - name: Ejecutar HTMLHint
      run: htmlhint

    - name: Mostrar resultados
      run: |
        if [ -s htmlhint.js ]; then
          echo "**Se han encontrado errores en el HTML.**"
          cat htmlhint.js  # Muestra los errores directamente en la consola
        else
          echo "**El HTML es válido.**"
        fi
